'use client'

import {PrivyProvider} from '@privy-io/react-auth';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <PrivyProvider
          appId="cmel4o5h7028ejp0b5qhp9cv6"
          clientId="client-WY6Pq8bjA29WLFWc2gfiPb1yTAMhH2kv81uWogFiEFoi9"
          config={{
            // Create embedded wallets for users who don't have a wallet
            embeddedWallets: {
              ethereum: {
                createOnLogin: 'users-without-wallets'
              }
            }
          }}
        >
       {children}
       </PrivyProvider>
      </body>
    </html>
  );
}
